"""Add CASCADE delete to order_products foreign key

Revision ID: 209e9d107b50
Revises: 5c324fd04d09
Create Date: 2026-01-02 11:38:19.169921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '209e9d107b50'
down_revision: Union[str, None] = '5c324fd04d09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('order_products_order_id_fkey'), 'order_products', type_='foreignkey')
    op.create_foreign_key(None, 'order_products', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_products', type_='foreignkey')
    op.create_foreign_key(op.f('order_products_order_id_fkey'), 'order_products', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###
