"""Simplify discount table to minimum_threshold only

Revision ID: 5c324fd04d09
Revises: 90904c3bf79d
Create Date: 2026-01-02 11:16:57.071640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c324fd04d09'
down_revision: Union[str, None] = '90904c3bf79d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add new column as nullable first
    op.add_column('discounts', sa.Column('minimum_threshold', sa.Float(), nullable=True))
    
    # Copy data from min_amount to minimum_threshold
    op.execute('UPDATE discounts SET minimum_threshold = min_amount WHERE minimum_threshold IS NULL')
    
    # Now make it non-nullable
    op.alter_column('discounts', 'minimum_threshold', nullable=False)
    
    # Drop old columns
    op.drop_column('discounts', 'min_amount')
    op.drop_column('discounts', 'max_amount')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discounts', sa.Column('max_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('discounts', sa.Column('min_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('discounts', 'minimum_threshold')
    # ### end Alembic commands ###
