"""Add products and order_products tables with product_count

Revision ID: 90904c3bf79d
Revises: 96cdf24b06ba
Create Date: 2026-01-02 11:04:53.918440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90904c3bf79d'
down_revision: Union[str, None] = '96cdf24b06ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('discount_percent', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('product_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'product_count')
    op.drop_column('orders', 'discount_percent')
    # ### end Alembic commands ###
